### ISSUE TITLE
IO.js Cannot find json data unless .json extension is included...

### ISSUE THREAD

**Issue by alexisvincent** [rvagg/node-boganipsum#1]
Error: Cannot find module './clean_words' from '/usr/src/app/node_modules/boganipsum'

Fix:

Add .json to each require. Pull request to follow

**Comment by rvagg** [comment]
what version of io.js are you using? perhaps you have something else loaded in your environment that is stoping this, babel? coffeescript?

```
$ ./boganipsum 
Watch out for the bottlo no worries he hasn't....
```

**Comment by rvagg** [comment]
```
$ node -v
v2.3.2-nightly20150625dcbb9e1da6
```

**Comment by alexisvincent** [comment]
It's quite possible the issue lies with module-deps, but I find this strange. Ill see if I can narrow it down

**Comment by alexisvincent** [comment]
So the issue is with substack/node-resolve.
https://github.com/substack/node-resolve/issues/19

Fixed by the open pr: https://github.com/substack/node-resolve/pull/20

**Comment by rvagg** [comment]
I'm not sure you're going to get far with that, I think substack prefers to explicitly name the extensions. Reopen the PR here if you don't end up getting anywhere and get frustrated with the lack of progress.

**Comment by alexisvincent** [comment]
Thanks, I've just noticed that the pr in question is 8 months old 11 months old. :/ I almost want to reopen this, however I'm sure I'll get this issue again with another project. I'll try see what can be done.
